### ISSUE TITLE
How many API requests

### ISSUE THREAD

**Issue by MrKakti** [scallensc/react-realtimeirl#10]
Hey my friend, can you tell me how many API requests are being made per hour? The linked services have a limited number of free requests, and I don’t want any unpleasant surprises. :)

**Comment by scallensc** [comment]
For the neighbourhood display,
it uses the reverse geocoding API, with a call being made once every 10 seconds. You would need to stream for 24 hours a day for 12 days before hitting the 100k request limit on that API before getting charged.

For tiles, unlimited tile requests after the view is initialised.

If you use the overlay as provided, I would not expect you to receive any charges, as I have not in over 2 years of development. 

If you're adding multiple instances for some reason, that's up to you to determine.

**Comment by MrKakti** [comment]
Thank you for your quick reply. Could you maybe help me with one more thing? I don't want to open a new topic for it because it's probably just a small thing. I'm not able to disable the animation; it should remain permanently visible. Is this correct, or where should I write this?

`.weather-container {
    disableAnimation
  position: absolute;
  width: 100vw;
  height: 100vh;
  right: 0;
  top: 0;
  text-align: right;
  font-family: 'Anek Latin', sans-serif;
  color: #fff;
  text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;
  font-size: 20px;
}`

`.neighbourhood-container {
    disableAnimation 
        position: absolute;
    width: 100vw;
    height: 100vh;
    right: 10px;
    top: -4px;
    text-align: right;
    font-family: 'Hiragino Kaku Gothic Pro', 'Blinker', sans-serif;
    color: #fff;
    text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;
    will-change: transform;
    transition: transform 0.1s linear;
}`

**Comment by scallensc** [comment]
Please read the documentation, this is covered in the section _**URL Parameters**_.
