### ISSUE TITLE
auto start on windows boot up

### ISSUE THREAD

**Issue by RookieKiwi** [scallensc/react-realtimeirl#2]
hey mate,
  sorry to bother you i know this is more of a support issue then code based but i wasnt sure how to contact you. i was wondering how would one go about making this awesome overlay start on bootup in windows ? i want to host this on a windows server that runs my obs on bootup.

**Comment by scallensc** [comment]
Hey mate, I'd take a look into pm2, I use it to manage persistent node apps on Linux systems, I believe it's available on Windows as well,  but haven't tried it myself, docs here:  
https://pm2.keymetrics.io/docs/usage/startup/  

If you're in the muxable discord just send me a message there, or DM me, cortex7846 and I'll try to help you sort it out.
